// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfkMJZwgf6RMllbqgWY5ZYCGVEJTSglok',
    appId: '1:254177074533:android:934304c360260a357c158c',
    messagingSenderId: '254177074533',
    projectId: 'neuroproject-882da',
    storageBucket: 'neuroproject-882da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjr3MAabzyYcwHK0gJPsDFJYkBZxLYqZs',
    appId: '1:254177074533:ios:d07e84ec5c173ed67c158c',
    messagingSenderId: '254177074533',
    projectId: 'neuroproject-882da',
    storageBucket: 'neuroproject-882da.appspot.com',
    iosClientId: '254177074533-2v3g84apu74hpibcu0pjj5rh5if08760.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
